name: Deploy PetsTracker

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-pets:latest .

      - name: Stop old container
        run: |
          docker stop my-pets || true
          docker rm my-pets || true

      - name: Run new container
        run: |
          docker run -d \
            --name my-pets \
            -p 80:8080 \
            --env-file /home/deployer/apps/my-pets/envs/dev.env \
            my-pets:latest
